name: Publish Docker image

on:
  push:
    branches:
      - main  # Publica la imagen en cada push a la rama main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Usa la versión más reciente

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Actualización de versión

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3  # Actualización de versión
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5  # Actualización de versión
        with:
          context: .
          push: true
          tags: ghcr.io/collanteslu/node-docker-package/my-express-app:latest
